/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminRulesRouteImport } from './routes/admin.rules'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as FacultyApprovalsRouteImport } from './routes/faculty.approvals'
import { Route as FacultyCoursesRouteImport } from './routes/faculty.courses'
import { Route as FacultyHistoryRouteImport } from './routes/faculty.history'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentHistoryRouteImport } from './routes/student.history'
import { Route as StudentNotificationsRouteImport } from './routes/student.notifications'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentSwapsIndexRouteImport } from './routes/student.swaps.index'
import { Route as StudentSwapsCreateRouteImport } from './routes/student.swaps.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/admin/audit-log',
  path: '/admin/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/faculty/',
  path: '/faculty/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyApprovalsRoute = FacultyApprovalsRouteImport.update({
  id: '/faculty/approvals',
  path: '/faculty/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyCoursesRoute = FacultyCoursesRouteImport.update({
  id: '/faculty/courses',
  path: '/faculty/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyHistoryRoute = FacultyHistoryRouteImport.update({
  id: '/faculty/history',
  path: '/faculty/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHistoryRoute = StudentHistoryRouteImport.update({
  id: '/student/history',
  path: '/student/history',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/student/notifications',
  path: '/student/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/student/timetable',
  path: '/student/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSwapsIndexRoute = StudentSwapsIndexRouteImport.update({
  id: '/student/swaps/',
  path: '/student/swaps/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentSwapsCreateRoute = StudentSwapsCreateRouteImport.update({
  id: '/student/swaps/create',
  path: '/student/swaps/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/rules': typeof AdminRulesRoute
  '/faculty/approvals': typeof FacultyApprovalsRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/history': typeof FacultyHistoryRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/swaps/create': typeof StudentSwapsCreateRoute
  '/student/swaps/': typeof StudentSwapsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/rules': typeof AdminRulesRoute
  '/faculty/approvals': typeof FacultyApprovalsRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/history': typeof FacultyHistoryRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/admin': typeof AdminIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/swaps/create': typeof StudentSwapsCreateRoute
  '/student/swaps': typeof StudentSwapsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/rules': typeof AdminRulesRoute
  '/faculty/approvals': typeof FacultyApprovalsRoute
  '/faculty/courses': typeof FacultyCoursesRoute
  '/faculty/history': typeof FacultyHistoryRoute
  '/student/history': typeof StudentHistoryRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/admin/': typeof AdminIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/swaps/create': typeof StudentSwapsCreateRoute
  '/student/swaps/': typeof StudentSwapsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/audit-log'
    | '/admin/rules'
    | '/faculty/approvals'
    | '/faculty/courses'
    | '/faculty/history'
    | '/student/history'
    | '/student/notifications'
    | '/student/timetable'
    | '/admin/'
    | '/faculty/'
    | '/student/'
    | '/student/swaps/create'
    | '/student/swaps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/audit-log'
    | '/admin/rules'
    | '/faculty/approvals'
    | '/faculty/courses'
    | '/faculty/history'
    | '/student/history'
    | '/student/notifications'
    | '/student/timetable'
    | '/admin'
    | '/faculty'
    | '/student'
    | '/student/swaps/create'
    | '/student/swaps'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/audit-log'
    | '/admin/rules'
    | '/faculty/approvals'
    | '/faculty/courses'
    | '/faculty/history'
    | '/student/history'
    | '/student/notifications'
    | '/student/timetable'
    | '/admin/'
    | '/faculty/'
    | '/student/'
    | '/student/swaps/create'
    | '/student/swaps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminRulesRoute: typeof AdminRulesRoute
  FacultyApprovalsRoute: typeof FacultyApprovalsRoute
  FacultyCoursesRoute: typeof FacultyCoursesRoute
  FacultyHistoryRoute: typeof FacultyHistoryRoute
  StudentHistoryRoute: typeof StudentHistoryRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
  AdminIndexRoute: typeof AdminIndexRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentSwapsCreateRoute: typeof StudentSwapsCreateRoute
  StudentSwapsIndexRoute: typeof StudentSwapsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/admin/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/faculty'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/approvals': {
      id: '/faculty/approvals'
      path: '/faculty/approvals'
      fullPath: '/faculty/approvals'
      preLoaderRoute: typeof FacultyApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/courses': {
      id: '/faculty/courses'
      path: '/faculty/courses'
      fullPath: '/faculty/courses'
      preLoaderRoute: typeof FacultyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/history': {
      id: '/faculty/history'
      path: '/faculty/history'
      fullPath: '/faculty/history'
      preLoaderRoute: typeof FacultyHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/history': {
      id: '/student/history'
      path: '/student/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof StudentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/student/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/swaps/': {
      id: '/student/swaps/'
      path: '/student/swaps'
      fullPath: '/student/swaps/'
      preLoaderRoute: typeof StudentSwapsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/swaps/create': {
      id: '/student/swaps/create'
      path: '/student/swaps/create'
      fullPath: '/student/swaps/create'
      preLoaderRoute: typeof StudentSwapsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminRulesRoute: AdminRulesRoute,
  FacultyApprovalsRoute: FacultyApprovalsRoute,
  FacultyCoursesRoute: FacultyCoursesRoute,
  FacultyHistoryRoute: FacultyHistoryRoute,
  StudentHistoryRoute: StudentHistoryRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
  AdminIndexRoute: AdminIndexRoute,
  FacultyIndexRoute: FacultyIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentSwapsCreateRoute: StudentSwapsCreateRoute,
  StudentSwapsIndexRoute: StudentSwapsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
