export enum SwapRequestStatus {
  OPEN = 'OPEN',
  MATCHED = 'MATCHED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum NotificationType {
  SWAP_CREATED = 'SWAP_CREATED',
  SWAP_MATCHED = 'SWAP_MATCHED',
  SWAP_PENDING_APPROVAL = 'SWAP_PENDING_APPROVAL',
  SWAP_APPROVED = 'SWAP_APPROVED',
  SWAP_REJECTED = 'SWAP_REJECTED',
  TIMETABLE_UPDATED = 'TIMETABLE_UPDATED',
}

export enum RuleCheckCode {
  ENROLLMENT_OWNERSHIP = 'ENROLLMENT_OWNERSHIP',
  SAME_COURSE = 'SAME_COURSE',
  CLASH_CHECK = 'CLASH_CHECK',
  ELIGIBILITY_CHECK = 'ELIGIBILITY_CHECK',
  CAPACITY_CHECK = 'CAPACITY_CHECK',
  DEADLINE_CHECK = 'DEADLINE_CHECK',
  MUTUAL_CHECK = 'MUTUAL_CHECK',
}
